nginx:
  restart: unless-stopped
  build: ./nginx
  links:
    - grafana:graf
  ports:
    - "80:80"

grafana:
  restart: unless-stopped
  build: ./grafana
  volumes:
    - grafana-storage:/var/lib/grafana
  hostname: grafana
  expose:
    - 3000